name: 'RClone GitHub Action'
description: 'A GitHub Action that wraps the RClone CLI, allowing you to easily integrate RClone commands into your CI/CD workflows.'
author: 'Ivan Rakic'
branding:
  icon: 'upload-cloud'
  color: 'green'

inputs:
  rclone_conf:
    description: 'RClone configuration content'
    required: true
  command:
    description: 'Command to pass to rclone'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - -e "GITHUB_OUTPUT"