name: 'RClone GitHub Action'
description: 'A GitHub Action that wraps the RClone CLI, allowing you to easily integrate RClone commands into your CI/CD workflows.'
author: 'Ivan Rakic'
branding:
  icon: 'upload-cloud'
  color: 'green'

inputs:
  rclone_conf:
    description: 'RClone configuration content'
    required: true
  command:
    description: 'Arguments to pass to the RClone command'
    required: true

outputs:
  rclone_output:
    description: 'The output of the RClone command'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    RCLONE_CONF: ${{ inputs.rclone_conf }}
  args:
    - ${{ inputs.command }}